### ISSUE TITLE
As a <actor>, I want to <action object> so that I can <action intent>

### ISSUE THREAD

**Issue by waiyan13** [waiyan13/kima-guitar-api#1]
## Acceptance Criteria

Feature: <name of the feature related to story>

    Scenario: when logging into the application
        Given the admin has valid credentials
        When the admin submits login details
        Then the admin should be redirected to admin dashboard

    Scenario: when logging into the application
        Given the admin has invalid credentials
        When the admin submits login details
        Then the admin should be prompted with error message

## Tasks List

- [ ] Setup SQLAlchemy and alembic
- [ ] Migrate and seed user table
- [ ] Create base route and response
- [ ] Create User model and schema
