### ISSUE TITLE
As a <actor>, I want to <action object> so that I can <action intent>

### ISSUE THREAD

**Issue by waiyan13** [waiyan13/kima-guitar-api#1]
## Acceptance Criteria

Feature: Authentication

    Scenario: when logging into the application
        Given the admin has valid credentials
        When the admin submits login details
        Then the admin should be redirected to admin dashboard

    Scenario: when logging into the application
        Given the admin has invalid credentials
        When the admin submits login details
        Then the admin should be prompted with error message

## Tasks List

- [ ] Setup Laravel Spatie
- [ ] Seed admin user with custom password
- [ ] Setup Laravel Passport
- [ ] Create authentication form requests
- [ ] Create authentication controller
- [ ] Create method to accept authentication request
- [ ] Prepare response for incorrect authentication
- [ ] Generate access token and refresh token for correct authentication
- [ ] Send refresh token as cookie
- [ ] Revoke refresh token when it expires
